//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';
export const DISABLE_LOADING = 'DISABLE_LOADING';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';
export const SET_TOKEN = 'SET_TOKEN';
export const LOGIN_GOOGLE_AUTH = 'LOGIN_GOOGLE_AUTH';
export const LOGIN_GOOGLE_AUTH_SUCCESS = 'LOGIN_GOOGLE_AUTH_SUCCESS';

// input
export const SET_USERNAME = 'SET_USERNAME';
export const SET_PASSWORD = 'SET_PASSWORD';
export const CLEAR_FORM = 'CLEAR_FORM';

// register
export const LOGIN_FROM_REGISTER = 'LOGIN_FROM_REGISTER';

// set new user
export const SET_NEW_USER = 'SET_NEW_USER';
export const SET_USER_REGISTERED = 'SET_USER_REGISTERED';
export const SET_EXPLORE = 'SET_EXPLORE';
export const SET_USER_ALREADY_EXPLORED = 'SET_USER_ALREADY_EXPLORED';
// set phone
export const SET_USER_PHONE_UPDATED = 'SET_USER_PHONE_UPDATED';
export const SET_USER_SELLER_LOGIN = 'SET_USER_SELLER_LOGIN';